# Generated by Django 2.2.1 on 2019-05-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistelement',
            old_name='link',
            new_name='data',
        ),
    ]
