# Generated by Django 2.1.7 on 2019-04-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='link',
            new_name='link2',
        ),
    ]
