# Generated by Django 2.1.7 on 2019-04-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0003_auto_20190405_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='a',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
