# Generated by Django 2.1.7 on 2019-04-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0004_playlist_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='a',
        ),
    ]
