# Generated by Django 2.1.7 on 2019-04-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0005_remove_playlist_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='link',
            new_name='link_id',
        ),
        migrations.AddField(
            model_name='playlistelement',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wedj.Playlist'),
        ),
    ]
