# Generated by Django 2.1.7 on 2019-04-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0006_auto_20190405_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='link_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='playlistelement',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
