# Generated by Django 2.2 on 2019-04-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0007_auto_20190405_1956'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistelement',
            unique_together={('playlist', 'order')},
        ),
    ]
