# Generated by Django 2.2 on 2019-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedj', '0008_auto_20190406_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistelement',
            name='order',
            field=models.IntegerField(),
        ),
    ]
